export const DASHBOARD_ACTION_TYPE = {
  SET_SHOW_MODAL_PASSWORD: 'dashboard/SET_SHOW_MODAL_PASSWORD',
  SET_SHOW_MODAL_DELETE: 'dashboard/SET_SHOW_MODAL_DELETE',
  SET_CONFIRM_DELETE: 'dashboard/SET_CONFIRM_DELETE',
  SET_IS_CHANGING: 'dashboard/SET_IS_CHANGING',
};
