export const SUB_CATEGORIES_ACTION_TYPE = {
  SET_SUB_CATEGORIES: 'sub-categories/SET_SUB_CATEGORIES',
  FETCH_SUB_CATEGORIES_START: 'sub-categories/FETCH_SUB_CATEGORIES_START',
  FETCH_SUB_CATEGORIES_SUCCESS: 'sub-categories/FETCH_SUB_CATEGORIES_SUCCESS',
  FETCH_SUB_CATEGORIES_FAILED: 'sub-categories/FETCH_SUB_CATEGORIES_FAILED',
  SET_SEARCH_TEXT: 'sub-categories/SET_SEARCH_TEXT',
};
