export const SHOP_ACTION_TYPE = {
  SET_CATEGORIES: 'shop/SET_CATEGORIES',
  SET_SUB_CATEGORIES: 'shop/SET_SUB_CATEGORIES',
  SET_PRODUCTS: 'shop/SET_PRODUCTS',
  SET_CATEGORIES_SEARCH_TEXT: 'shop/SET_CATEGORIES_SEARCH_TEXT',
  SET_SUB_CATEGORIES_SEARCH_TEXT: 'shop/SET_SUB_CATEGORIES_SEARCH_TEXT',
};
