export const CATEGORIES_ACTION_TYPE = {
  SET_CATEGORIES: 'categories/SET_CATEGORIES',
  FETCH_CATEGORIES_START: 'categories/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'categories/FETCH_CATEGORIES_FAILED',
  SET_SEARCH_TEXT: 'categories/SEARCH_TEXT',
};
